# Generated by Django 5.0.1 on 2024-02-05 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0005_iqeauser_username_alter_iqeauser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('flow', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimador.iqeauser')),
                ('reuso_cotizacion', models.ManyToManyField(blank=True, related_name='reuso_cotizacion', to='estimador.pricevalue')),
                ('waste_water_cotizacion', models.ManyToManyField(blank=True, related_name='waste_water_cotizacion', to='estimador.pricevalue')),
                ('water_cotizacion', models.ManyToManyField(blank=True, related_name='water_cotizacion', to='estimador.pricevalue')),
                ('project_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimador.project')),
            ],
        ),
    ]
