# Generated by Django 5.0.1 on 2024-02-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0006_pricevalue_project_cotizacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectData',
        ),
    ]
