# Generated by Django 5.0.1 on 2024-02-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0014_pricevalue_contizacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
