# Generated by Django 5.0.1 on 2024-02-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0015_delete_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricevalue',
            old_name='contizacion',
            new_name='cotizacion',
        ),
    ]
