# Generated by Django 5.0.1 on 2024-02-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0016_rename_contizacion_pricevalue_cotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricevalue',
            name='cotizacion',
        ),
        migrations.AddField(
            model_name='pricevalue',
            name='cotizacion',
            field=models.ManyToManyField(blank=True, db_index=True, to='estimador.cotizacion'),
        ),
    ]
