# Generated by Django 5.0.1 on 2024-02-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0018_reusosystem_alter_cotizacion_reuso_cotizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastewatersystem',
            name='cotizacion',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='reuso_cotizacion',
            field=models.ManyToManyField(blank=True, related_name='reusoCotizacion', to='estimador.reusosystem'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='waste_water_cotizacion',
            field=models.ManyToManyField(blank=True, related_name='wasteWaterCotizacion', to='estimador.wastewatersystem'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='water_cotizacion',
            field=models.ManyToManyField(blank=True, related_name='waterCotizacion', to='estimador.watersystem'),
        ),
    ]
