# Generated by Django 5.0.1 on 2024-02-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0019_remove_wastewatersystem_cotizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reusosystem',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='watersystem',
            name='cotizacion',
        ),
    ]
