# Generated by Django 5.0.1 on 2024-02-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0020_remove_reusosystem_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersystem',
            name='cotizacion',
            field=models.ManyToManyField(blank=True, db_index=True, to='estimador.cotizacion'),
        ),
    ]
