# Generated by Django 5.0.1 on 2024-02-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0021_watersystem_cotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watersystem',
            name='cotizacion',
        ),
    ]
