# Generated by Django 5.0.1 on 2024-02-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0022_remove_watersystem_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iqeauser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
