# Generated by Django 5.0.1 on 2024-02-28 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0023_alter_iqeauser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreciosReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_categories', models.CharField(blank=True, choices=[('water_cotizacion', 'Water Cotizacion'), ('waste_water_cotizacion', 'Waste Water Cotizacion'), ('reuso_cotizacion', 'Reuso Cotizacion')], max_length=255, null=True)),
                ('system_type', models.CharField(blank=True, choices=[('osmosis', 'osmosis'), ('suavisador', 'Suavisador'), ('filtracion', 'Filtracion'), ('pretratamiento', 'Pretratamiento'), ('lodosActivados', 'Lodos Activados'), ('bioFiltracion', 'Filtracion'), ('mbbr', 'mbbr'), ('osmosisReuso', 'Osmosis Reuso'), ('ultrafiltracion', 'Ultrafiltracion')], max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioRefPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flujo', models.DecimalField(decimal_places=2, max_digits=3)),
                ('precioFinal', models.DecimalField(decimal_places=2, max_digits=3)),
                ('unidad', models.CharField(choices=[('m3/d', 'm3/d'), ('m3/h', 'm3/h'), ('lts/hr', 'lts/hr'), ('gpd', 'GPD'), ('gpm', 'GPM')])),
                ('consideraciones', models.CharField(blank=True, max_length=255, null=True)),
                ('precios_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_ref_points', to='estimador.preciosreferencia')),
            ],
        ),
    ]
