# Generated by Django 5.0.1 on 2024-02-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0024_preciosreferencia_preciorefpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciorefpoint',
            name='flujo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='preciorefpoint',
            name='precioFinal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
