# Generated by Django 5.0.1 on 2024-02-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0025_alter_preciorefpoint_flujo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciorefpoint',
            name='currency',
            field=models.CharField(blank=True, choices=[('m3/d', 'm3/d'), ('m3/h', 'm3/h'), ('lts/hr', 'lts/hr'), ('gpd', 'GPD'), ('gpm', 'GPM')], null=True),
        ),
    ]
