# Generated by Django 5.0.1 on 2024-03-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0027_systemcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtype',
            name='title',
            field=models.CharField(blank=True, choices=[('osmosis', 'Osmosis Inversa'), ('suavisador', 'Suavisador'), ('filtracion', 'Filtracion'), ('pretratamiento', 'Pretratamiento'), ('lodosActivados', 'Lodos Activados'), ('bioFiltracion', 'BioFiltracion'), ('mbbr', 'MBBR'), ('osmosisReuso', 'Osmosis Reuso'), ('ultrafiltracion', 'Ultrafiltracion')], null=True),
        ),
    ]
