# Generated by Django 5.0.1 on 2024-03-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0029_alter_systemcategory_title_alter_systemtype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcategory',
            name='title',
            field=models.CharField(blank=True, choices=[('water_cotizacion', 'Clean Water'), ('waste_water_cotizacion', 'Waste Water'), ('reuso_cotizacion', 'Reuso Water')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='systemtype',
            name='title',
            field=models.CharField(blank=True, choices=[('osmosis', 'Osmosis Inversa'), ('suavisador', 'Suavisador')], max_length=30, null=True),
        ),
    ]
