# Generated by Django 5.0.1 on 2024-03-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0030_alter_systemcategory_title_alter_systemtype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciorefpoint',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'usd'), ('MXN', 'mxn')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='preciorefpoint',
            name='unidad',
            field=models.CharField(choices=[('m3/d', 'm3/d'), ('m3/h', 'm3/h'), ('lts/hr', 'lts/hr'), ('gpd', 'GPD'), ('gpm', 'GPM')], max_length=10),
        ),
    ]
