# Generated by Django 5.0.1 on 2024-03-01 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0032_rename_water_cotizacion_cotizacion_clean_water_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='system_cotizacion',
            field=models.ManyToManyField(blank=True, related_name='system_cotizacion', to='estimador.systemcotizacion'),
        ),
        migrations.AddField(
            model_name='systemcotizacion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimador.iqeauser'),
        ),
    ]
