# Generated by Django 5.0.1 on 2024-03-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimador', '0034_alter_cotizacion_clean_water_system_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReusoSystem',
        ),
        migrations.DeleteModel(
            name='WasteWaterSystem',
        ),
        migrations.DeleteModel(
            name='WaterSystem',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='system_cotizacion',
        ),
        migrations.RemoveField(
            model_name='systemcotizacion',
            name='user',
        ),
    ]
